n = input('Digite algo: ')
print(f'O tipo primitivo desse valor é {type(n)}')
print(f'Só tem espacos? {n.isspace()}')
print(f'É um número? {n.isalnum()}')
print(f'É alfabético? {n.isalpha()}')
print(f'É alfanumérico? {n.isalpha()}')
print(f'Está em maiúsculas? {n.isupper()}')
print(f'Está em minúsculas? {n.islower()}')
print(f'Está capitalizada? {n.istitle()}')
